In [2]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = data.iloc[:, 3:-1].values
Y = data.iloc[:, -1].values

In [6]:
X, Y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [8]:
label_encoder_1 = LabelEncoder()
X[:, 1] = label_encoder_1.fit_transform(X[:, 1])
label_encoder_2 = LabelEncoder()
X[:, 2] = label_encoder_2.fit_transform(X[:, 2])

In [9]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [11]:
X = X[:, 1:]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_shape=(11,)))
    classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

In [18]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [19]:
classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size':  [16, 32],
             'epochs': [25, 50], 
             'optimizer': ['Adam', 'Adadelta']}
grid_search = GridSearchCV(estimator=classifier, param_grid=parameters)

In [ ]:
grid_search.fit(X_train, Y_train)

Epoch 1/25
5333/5333 [==============================] - 1s 273us/step - loss: 0.5532 - acc: 0.7973
Epoch 2/25
5333/5333 [==============================] - 1s 229us/step - loss: 0.4385 - acc: 0.7973
Epoch 3/25
5333/5333 [==============================] - 2s 322us/step - loss: 0.4327 - acc: 0.7973
Epoch 4/25
5333/5333 [==============================] - 1s 243us/step - loss: 0.4296 - acc: 0.7973
Epoch 5/25
5333/5333 [==============================] - 1s 239us/step - loss: 0.4272 - acc: 0.7973
Epoch 6/25
5333/5333 [==============================] - 1s 279us/step - loss: 0.4240 - acc: 0.7973
Epoch 7/25
5333/5333 [==============================] - 1s 272us/step - loss: 0.4220 - acc: 0.8140
Epoch 8/25
5333/5333 [==============================] - 1s 265us/step - loss: 0.4199 - acc: 0.8192
Epoch 9/25
5333/5333 [==============================] - 2s 334us/step - loss: 0.4187 - acc: 0.8258
Epoch 10/25
5333/5333 [==============================] - 2s 341us/step - loss: 0.4172 - acc: 0.8266
Epoch 11/

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



8000/8000 [==============================] - 2s 204us/step - loss: 0.4326 - acc: 0.7951
Epoch 3/50
8000/8000 [==============================] - 1s 165us/step - loss: 0.4228 - acc: 0.8139
Epoch 4/50
8000/8000 [==============================] - 1s 183us/step - loss: 0.4138 - acc: 0.8291
Epoch 5/50
8000/8000 [==============================] - 1s 162us/step - loss: 0.4069 - acc: 0.8334
Epoch 6/50
8000/8000 [==============================] - 1s 124us/step - loss: 0.4040 - acc: 0.8331
Epoch 7/50
8000/8000 [==============================] - 1s 124us/step - loss: 0.4021 - acc: 0.8342
Epoch 8/50
8000/8000 [==============================] - 2s 222us/step - loss: 0.4009 - acc: 0.8348
Epoch 9/50
8000/8000 [==============================] - 2s 215us/step - loss: 0.3999 - acc: 0.8354
Epoch 10/50
8000/8000 [==============================] - 2s 206us/step - loss: 0.3992 - acc: 0.8346
Epoch 11/50
8000/8000 [==============================] - 1s 163us/step - loss: 0.3980 - acc: 0.8339
Epoch 12/50
8000/80

In [24]:
best_param = grid_search.best_params_
best_score = grid_search.best_score_

In [26]:
print("Best parameters {} - Best score {}".format(best_param, best_score))

Best parameters {'batch_size': 32, 'epochs': 50, 'optimizer': 'Adadelta'} - Best score 0.8572500000372529
